### ISSUE TITLE
Broken in OS X 10.9 Mavericks

### ISSUE THREAD

**Issue by Enf0** [glarizza/puppet-property_list_key#12] opened 2013-10-04 18:30 UTC
Seems this plugin is broken in Mavericks. All my property_list_key resources now return this error:

``` bash
Error: /Stage[main]/Zz_munki/Property_list_key[ClientIdentifier]: Could not evaluate: Unable to open the file /Library/Preferences/ManagedInstalls.plist.  NameError: #<NameError: uninitialized constant OSX>
```

**Comment by groob** [comment] 2013-10-07 04:22
Looks like this is happening because 10.9 changed default ruby to 2.0.0

**Comment by am** [comment] 2013-10-13 21:33
I was looking into [this](https://gist.github.com/nsforge/6861400) but didn't work.

**Comment by alykhank** [comment] 2013-11-01 19:51
I managed to get similar functionality working on a clean install of Mavericks by using the boxen::osx_defaults resource type, example here: alykhank/our-boxen@b1b473fb45136b0be3ba6f13bc2324b2286d7295

**Comment by glarizza** [comment] 2013-12-17 04:01
Wow - I'm a bad person.  Alerts weren't getting sent to me. This should be fixed with https://github.com/glarizza/puppet-property_list_key/commit/13d26e008c16d59e46c4d9929496e036278998f5 - and the CFPropertyList Gem (version 2.2.5) PLEASE give it a shot and let me know!

**Comment by glarizza** [comment] 2013-12-17 04:26
As most already know - RubyCocoa isn't in Ruby 2.0.0 in Mavericks.  The new CFPropertyList provider is my recommended method, and I've committed that.  Closing this issue now, but PLEASE let me know if any issues arise and we can open it back up!

**Closed as completed** 2013-12-17 04:27 UTC

**Comment by ajordanow** [comment] 2013-12-17 23:41
Now after updating to 0.2.0 I'm getting:

```
Failed to load feature test for cfpropertylist: cannot load such file -- CFPropertyList
...
Error: Could not find a suitable provider for property_list_key
```

My CFPropertyList version is 2.2.5 (reported by `gem`)

**Comment by glarizza** [comment] 2013-12-17 23:56
That's not good - are you using rbenv, rvm, or anything like that - or modifying system ruby?  Can you give me the output of `gem list` please?

**Comment by ajordanow** [comment] 2013-12-18 00:14
I'm running plain maverics install (as I'm recreating my new box from scratch using boxen).  
My gems are:

```
bundler (1.3.5)
CFPropertyList (2.2.5)
diff-lcs (1.2.5)
facter (1.7.3)
hiera (1.3.0)
json_pure (1.8.1)
libxml-ruby (2.7.0, 2.6.0)
metaclass (0.0.1)
mini_portile (0.5.2)
mocha (0.14.0)
nokogiri (1.6.1, 1.5.6)
puppet (3.3.2)
puppetlabs_spec_helper (0.4.1)
rake (10.1.0)
rake-compiler (0.9.2)
rgen (0.6.6)
rspec (2.14.1)
rspec-core (2.14.7)
rspec-expectations (2.14.4)
rspec-mocks (2.14.4)
rspec-puppet (1.0.1)
sqlite3 (1.3.8, 1.3.7)
watchr (0.7)
```

The only thing I've done is uninstalling CFPropertyList 2.2.0 (hoped that will resolve the problem but it didn't). Actually I've got the same error messages when I remove the CFPropertyList completely.

**Comment by glarizza** [comment] 2013-12-18 00:20
I will need to spin up a new Mavericks VM to test this out - do you get a message about "The version of CFPropertyList on the system is too old. Please ensure that you have version '2.2.5' of the CFPropertyList gem..." at all during the run?

**Comment by glarizza** [comment] 2013-12-18 00:21
I'm rescuing an ArgumentError, but am wondering if there's another Exception Class that's NOT getting rescued.  Can you grab the result of `boxen --debug` into a gist somewhere (with sensitive info stripped if need be)?

**Comment by ajordanow** [comment] 2013-12-18 00:36
Sure - https://gist.github.com/ajordanow/8015400 (no signs of exceptions though)

**Comment by glarizza** [comment] 2013-12-18 17:22
Are you able to test this independent of Boxen?  Inside the module is a `tests/property_list.pp` file which should create some entries in `/tmp/com.puppetlabs.puppet`.  Can you run `puppet apply` against that file and produce the same error?  

I spun up a 10.9 VM this morning, pulled down my module, installed Facter/Puppet, did a `sudo gem install CFPropertyList -v 2.2.5`, set `$RUBYLIB`, and ran `puppet apply` against that test file without issue - so I couldn't reproduce the issue.  Can you start here?  I'll pull down my Boxen setup and try to trigger it on this node to see if I can reproduce the error, but as of yet haven't been able to reproduce it.

**Comment by glarizza** [comment] 2013-12-18 17:35
Also, it looks like Boxen successfully ran - so did `rbenv` get setup on your machine?  What does `rbenv versions` show? What about `rbenv global`?

**Comment by ajordanow** [comment] 2013-12-18 21:07
I have only ruby version that comes with Maverics, so no `rbenv` is installed (but I've installed it and the outcome is exactly the same - no matter what ruby version i'm using; tried with 2.0.0).

The strange thing is happening when I try to build the module. Look at the output of `rake build`:

```
rake aborted!
Could not autoload puppet/face/module/install: Error converting value for param 'modulepath': Could not find value for $confdir
/Library/Ruby/Gems/2.0.0/gems/puppet-3.3.2/lib/puppet/util/autoload.rb:68:in `rescue in load_file'
/Library/Ruby/Gems/2.0.0/gems/puppet-3.3.2/lib/puppet/util/autoload.rb:59:in `load_file'
/Library/Ruby/Gems/2.0.0/gems/puppet-3.3.2/lib/puppet/util/autoload.rb:76:in `block in loadall'
/Library/Ruby/Gems/2.0.0/gems/puppet-3.3.2/lib/puppet/util/autoload.rb:74:in `each'
/Library/Ruby/Gems/2.0.0/gems/puppet-3.3.2/lib/puppet/util/autoload.rb:74:in `loadall'
/Library/Ruby/Gems/2.0.0/gems/puppet-3.3.2/lib/puppet/util/autoload.rb:206:in `loadall'
/Library/Ruby/Gems/2.0.0/gems/puppet-3.3.2/lib/puppet/interface.rb:181:in `load_actions'
/Library/Ruby/Gems/2.0.0/gems/puppet-3.3.2/lib/puppet/interface.rb:72:in `define'
/Library/Ruby/Gems/2.0.0/gems/puppet-3.3.2/lib/puppet/face/module.rb:5:in `<top (required)>'
/Library/Ruby/Gems/2.0.0/gems/puppet-3.3.2/lib/puppet/interface/face_collection.rb:100:in `safely_require'
/Library/Ruby/Gems/2.0.0/gems/puppet-3.3.2/lib/puppet/interface/face_collection.rb:56:in `load_face'
/Library/Ruby/Gems/2.0.0/gems/puppet-3.3.2/lib/puppet/interface/face_collection.rb:17:in `[]'
/Library/Ruby/Gems/2.0.0/gems/puppet-3.3.2/lib/puppet/interface.rb:102:in `[]'
/Users/x/puppet-property_list_key/Rakefile:25:in `rescue in block in <top (required)>'
/Users/x/puppet-property_list_key/Rakefile:21:in `block in <top (required)>'
Tasks: TOP => build
(See full trace by running task with --trace)
```

So when I try to run the test I've got:

```
Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Invalid resource type property_list_key at /Users/x/puppet-property_list_key/tests/property_list.pp:6 on node rycyna.local
Wrapped exception:
Invalid resource type property_list_key
Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Invalid resource type property_list_key at /Users/x/puppet-property_list_key/tests/property_list.pp:6 on node rycyna.local
```

**Comment by glarizza** [comment] 2013-12-18 21:15
Try setting your RUBYLIB:

```
export RUBYLIB=/Users/x/puppet-property_list_key/lib
```

And then run the test again

**Comment by ajordanow** [comment] 2013-12-18 21:19
Set and got exactly same results (failures)

**Comment by glarizza** [comment] 2013-12-18 21:22
This failure is because Puppet cannot locate the type - setting RUBYLIB adds another path for Puppet to query for custom plugins.  Is there a permissions issue?  Are you running `puppet` as yourself or as `root` with `sudo`? If you're running with `sudo`, then `$RUBYLIB` needs set for the `root` user.  What's the path to `puppet` - what does `which puppet` return?

**Comment by ajordanow** [comment] 2013-12-18 21:46
I'm running `puppet` as myself. `RUBYLIB` points to correct directory. Puppet binary is `/opt/boxen/rbenv/shims/puppet`.

Partial success though :) I've managed to run the tests (`property_list.pp`) when I've specified modules path by hand:

```
puppet apply --modulepath=/Users/x ./property_list.pp
```

**Comment by glarizza** [comment] 2013-12-18 21:50
Gah, I totally overlooked `$modulepath` - good catch :)  Looks like it does work on 10.9 when CFP is being found by Ruby.

I'm now suspecting the Ruby library that Boxen is using....whether CFP is available there or not. `which puppet` is returning the `rbenv` shim, so `rbenv` is invariably being used - check which ruby version is being used by Boxen and see if CFP shows up there.  I'd start there :)

**Comment by ajordanow** [comment] 2013-12-20 07:04
The Ruby version was fine. I reckon it had something to do with bundler since `/opt/boxen/repo/.bundle/config` contained

```
BUNDLE_DISABLE_SHARED_GEMS: '1'
```

So `Gem.path` contained only `/opt/boxen/repo/.bundle/ruby/2.0.0` and system gems were not recognised.

When I've added CFP to `Gemfile` (and run `bundle`) it helped. 

By the way, I think require statement for CFP should be `require 'cfpropertylist'` (not `require 'CFPropertyList'`) - otherwise it'll fail on case-sensitive HFS volumes ;)

**Comment by glarizza** [comment] 2013-12-20 16:41
Thanks for clearing that up - I guarantee it will help someone in the future :) :+1: 

As for the require, I've had issues with it being lowercase in the past.  OS X especially has issues with case sensitivity on Gems that require it.  To test it out, I did the following:

```
(836) [glarizza@Satori] [puppet: 3.4.0-rc2] [ ] [master ⚡] [7]
└(~/src/puppet-property_list_key)▷ vim Gemfile
┌(837) [glarizza@Satori] [puppet: 3.4.0-rc2] [ ] [master ⚡]
└(~/src/puppet-property_list_key)▷ be gem list

*** LOCAL GEMS ***

bundler (1.4.0.rc.1)
CFPropertyList (2.2.5)
diff-lcs (1.2.5)
facter (1.7.3)
hiera (1.3.0)
json_pure (1.8.1)
libxml-ruby (2.7.0)
metaclass (0.0.1)
mocha (0.14.0)
puppet (3.3.2)
puppetlabs_spec_helper (0.4.1)
rake (10.1.0)
rake-compiler (0.9.2)
rgen (0.6.6)
rspec (2.14.1)
rspec-core (2.14.7)
rspec-expectations (2.14.4)
rspec-mocks (2.14.4)
rspec-puppet (1.0.1)
watchr (0.7)
┌(838) [glarizza@Satori] [puppet: 3.4.0-rc2] [ ] [master ⚡]
└(~/src/puppet-property_list_key)▷ vim Gemfile

## Edited the Gemfile to change the gem to 'cfpropertylist'

┌(839) [glarizza@Satori] [puppet: 3.4.0-rc2] [ ] [master ⚡]
└(~/src/puppet-property_list_key)▷ be gem list
Could not find gem 'cfpropertylist (>= 2.2.5) ruby' in the gems available on this machine.
Run `bundle install` to install missing gems.
┌(840) [glarizza@Satori] [puppet: 3.4.0-rc2] [ ] [master ⚡] [7]
└(~/src/puppet-property_list_key)▷ bundle install
Fetching gem metadata from http://rubygems.org/..........
Fetching gem metadata from http://rubygems.org/..
Resolving dependencies...
Retrying source fetch due to error (2/3): Could not find gem 'cfpropertylist (>= 2.2.5) ruby' in the gems available on this machine.
Resolving dependencies...
Retrying source fetch due to error (3/3): Could not find gem 'cfpropertylist (>= 2.2.5) ruby' in the gems available on this machine.
Resolving dependencies...
Could not find gem 'cfpropertylist (>= 2.2.5) ruby' in the gems available on this machine.
```

**Comment by cdenneen** [comment] 2014-02-11 02:31
ok so since shared gems are disabled by default in boxen... how is boxen supposed to use the system install CFP >2.2.5?

**Comment by glarizza** [comment] 2014-02-11 02:38
Your boxen repo should have a `Gemfile` in the root - you'll need to add a line for CFP.  The goal is to have a Gem JUST for Boxen (and not the system gems).  My line looks like so:

```
gem 'CFPropertyList',         '>= 2.2.6'
```
